# Generated by deploy_wizard.sh — 2026-03-14T06:01:08Z

gcp_project  = "mylab-20260313"
gcp_region   = "us-central1"
name_prefix  = "stratusai"
environment  = "prod"

enable_ai = true
ai_model  = "claude-sonnet-4-6"
api_key   = "sk-ant-api03-iTh3OBfGWq48edWKSRGYtlCh2wlU3rFgJyeYQ6MHonUYoXzyDF_0g0uSwB_1pgDfpidlQJxEdSnZJFJn8SLGyw-PRbU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"

scan_severity        = "MEDIUM"
enable_external_scan = true
external_scan_target = "34.133.91.79"

enable_scheduler    = false
schedule_expression = "0 8 * * 1"
